# docker-compose.yml
services:
  traefik:
    image: traefik:v2.4
    command: --api.insecure=true --providers.docker
    ports:
      - "8888:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false

  img2md:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.img2md.rule=PathPrefix(`/img2md`)"
      - "traefik.http.services.img2md.loadbalancer.server.port=7860"
    expose:
      - "7860"